schema_version: 1

context:
  version: "0.1.3"

package:
  name: jupyverse-yrooms
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupyverse-yrooms/jupyverse_yrooms-${{ version }}.tar.gz
    sha256: bcd3f70d738f7b05ba5cd08c973194147ccfad6d2cabac14650e0b96e70eb2cd

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build >=0.11.32,<0.12
  run:
    - python >=${{ python_min }}
    - anyio
    - anyioutils
    - httpx2 >=2.9.1,<3.0.0
    - pycrdt

tests:
  - python:
      imports: jupyverse_yrooms
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/api/yrooms
  summary: The API for Jupyverse's YRooms.

extra:
  recipe-maintainers:
    - davidbrochart
